/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconCaretBottom: typeof import('@element-plus/icons-vue')['CaretBottom']
    ElIconCaretTop: typeof import('@element-plus/icons-vue')['CaretTop']
    ElIconFiles: typeof import('@element-plus/icons-vue')['Files']
    ElIconNotebook: typeof import('@element-plus/icons-vue')['Notebook']
    ElIconPieChart: typeof import('@element-plus/icons-vue')['PieChart']
    ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElIconUser: typeof import('@element-plus/icons-vue')['User']
    ElIconUserFilled: typeof import('@element-plus/icons-vue')['UserFilled']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEpSearch: typeof import('~icons/ep/search')['default']
    IconEpWarning: typeof import('~icons/ep/warning')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpPieChart: typeof import('~icons/ep/pie-chart')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
